### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by amir-arad** [mathdroid/simple-raycaster#1]
I've tried to use this library in my playground project, but nothing happens. Am I missing something?

**Comment by mathdroid** [comment]
Hi @amir-arad , sorry I just replied. Are you still having the issue? I can not replicate the issue. Could you show me your `client.js`?

**Comment by amir-arad** [comment]
nope, my bad. was a typo in `client.js`.

Thanks for the example, too few of those going around!
